AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Regression FastAPI app on AWS Lambda

Globals:
  Function:
    Runtime: python3.11
    Timeout: 60
    MemorySize: 2048

Resources:
  RegressionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: regression-backend
      Handler: lambda_handler.handler
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
